modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"
[[mods]]
modId="butdaysblueprint"
version="1.0.0"
displayName="Butday's Blueprint"
logoFile="engineer_manuscript.png"
authors="butday"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"